name: Claude Code Action

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to respond to'
        required: true
        type: number

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  claude:
    # tweet-generationラベルがついたIssueのみ実行
    if: contains(github.event.issue.labels.*.name, 'tweet-generation')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
