name: Claude Code Action (OAuth)

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  claude:
    # tweet-generationラベルがついたIssueのみ実行
    if: contains(github.event.issue.labels.*.name, 'tweet-generation')
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト（必須）
      - name: Checkout repository
        uses: actions/checkout@v4

      # OAuth認証情報をSecretsに保存（初回のみ実行）
      - name: Setup Claude OAuth
        if: ${{ !secrets.CLAUDE_OAUTH_ACCESS_TOKEN }}
        uses: grll/claude-code-login@v1
        with:
          github_token: ${{ secrets.CLAUDE_OAUTH_SETUP_PAT }}
          access_token: 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
          refresh_token: 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
          expires_at: "1792472972066"

      # Claude Code Action (OAuth対応版)
      - uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CLAUDE_OAUTH_ACCESS_TOKEN: ${{ secrets.CLAUDE_OAUTH_ACCESS_TOKEN }}
          CLAUDE_OAUTH_REFRESH_TOKEN: ${{ secrets.CLAUDE_OAUTH_REFRESH_TOKEN }}
          CLAUDE_OAUTH_EXPIRES_AT: ${{ secrets.CLAUDE_OAUTH_EXPIRES_AT }}
