name: Claude Code Action

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  claude:
    # tweet-generationラベルがついたIssueのみ実行
    if: contains(github.event.issue.labels.*.name, 'tweet-generation')
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト（必須）
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # OAuth token (sk-ant-oat01-) でも動作する可能性あり
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        env:
          # OAuth tokenの場合はANTHROPIC_AUTH_TOKENも試せます
          ANTHROPIC_AUTH_TOKEN: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
